# Site settings
title: CaixaPreta
email: ikebanto@gmail.com
url: https://ikebanto.github.io
description: "Um mundo todo dentro de uma caixa!"
keywords: "Ilustrações, vetor, Web, Wordpress"
skills: "Web Developer - Graphic Artist - User Linux - User Experience Designer"
meta_author: Ike Banto

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: ikebanto

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
#  secondary: 2c3e50 #FD6E8A
  secondary: 0d1218 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: Ike Banto
  location: Campinas | São Paulo
  social: Siga nas Redes
  credits: Creditos

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/ikebanto
  - title: facebook
    url: https://fb.com/ikebanto
  - title: github
    url: http://github.com/ikebanto

# Postal address (add as many lines as necessary)
address:
  - line: Nos Becos e Esquinas
  - line: Campinas | São Paulo - Brasil

# Credits content
credits: 'Desenvolvido em Jekyll com <i class="fa fa-linux" aria-hidden="true"></i> e <i class="fa fa-heart" aria-hidden="true"></i> ! Seja Livre, use Gnu-Linux!'

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:title.html

# html minify
compress_html:
clippings: all
comments: all
endings: []
profile: false
